// This file is generated by npm run build:icons
  
  export type IconName =
	| "blockscout-logo"
	| "copy"
	| "info-circle"
	| "info"
	| "profile"
	| "social/discord-circle"
	| "social/github-circle"
	| "social/telegram-circle"
	| "social/x-circle"
	| "social/x"
	| "stats";
  