// This file is generated by npm run build:icons
  
  export type IconName =
	| "arrows/east-mini"
	| "blockscout-logo"
	| "copy"
	| "info-circle"
	| "info"
	| "merits-outline"
	| "profile"
	| "search"
	| "social/discord-circle"
	| "social/github-circle"
	| "social/telegram-circle"
	| "social/x-circle"
	| "social/x"
	| "star"
	| "stats"
	| "status/error"
	| "status/pending"
	| "status/success"
	| "status/warning";
  